services:
  - type: web
    name: minha-loja
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DB_PATH
        value: /var/data/loja.db
    disk:
      name: loja-dados
      mountPath: /var/data
      sizeGB: 1